name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask bandit flake8 pytest

      - name: Run Bandit (Security Scan)
        run: |
          bandit -r . -f json -o bandit_report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_report.json

      - name: Run Flake8 (Code Linter)
        run: |
          flake8 . --exit-zero

      - name: Run tests
        run: |
          pytest > result.log || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: result.log

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
